### ISSUE TITLE
No such file or directory: 'checkpoints/v3_2048/epoch_train/checkpoint_300_epoch.pth'

### ISSUE THREAD

**Issue by YaoDongAn** [birlrobotics/PMN#1]
Hello, thank you for your work. 
When I try to use the checkpoint of HICO-DET and V-COCO to reproduce the detection results in your paper,I encounter this question. But I can't find this file from the link you given.
Thank you very much.

**Comment by YaoDongAn** [comment]
> Hello, thank you for your work.
> When I try to use the checkpoint of HICO-DET and V-COCO to reproduce the detection results in your paper,I encounter this question. But I can't find this file from the link you given.
> Thank you very much.

**Comment by YaoDongAn** [comment]
> Hello, thank you for your work.
> When I try to use the checkpoint of HICO-DET and V-COCO to reproduce the detection results in your paper,I encounter this question. But I can't find this file from the link you given.
> Thank you very much.

**Comment by BIGJUN777** [comment]
Hello,

In the corresponding [code](https://github.com/birlrobotics/PMN/blob/dca0dee799aa834580238dbcef1709dc54f197dd/hico_eval.py#L130), we set a default path to the checkpoint file. You need to overwrite it there or just follow [here](https://github.com/birlrobotics/PMN#testing)  to assign the correct path to the checkpoints (_e.g._ './checkpoints/hico/xxx_checkpoint.pth') in the command.

**Comment by YaoDongAn** [comment]
> Hello,
> 
> In the corresponding [code](https://github.com/birlrobotics/PMN/blob/dca0dee799aa834580238dbcef1709dc54f197dd/hico_eval.py#L130), we set a default path to the checkpoint file. You need to overwrite it there or just follow [here](https://github.com/birlrobotics/PMN#testing) to assign the correct path to the checkpoints (_e.g._ './checkpoints/hico/xxx_checkpoint.pth') in the command.

Thank you for your reply. 
The the checkpoint files you provided kindly，are hico_checkpoint.pth and hico_checkpoint_600_epoch.pth. I assign the correct path. The first one can be loaded successfully but the second one can't. I'm wonder if the second checkpoint file is mistake?
Below is my screenshot. Thank you for your patience.
![2020-09-12 15-49-35屏幕截图](https://user-images.githubusercontent.com/48275107/92990517-b2b8ee00-f50f-11ea-8311-76a072d301bf.png)

**Comment by BIGJUN777** [comment]
Did you download the pre-trained checkpoints of PMN from [Here](https://github.com/birlrobotics/PMN#testing). I just shared the following files in that section instead of those (checkpoint_xxx_epoch.pth) showed in your screenshot. Please check it again.

![Screenshot from 2020-09-12 16-13-45](https://user-images.githubusercontent.com/35102882/92991110-db42e700-f513-11ea-85f9-e42cf5e4f7cb.png)

**Comment by YaoDongAn** [comment]
> Did you download the pre-trained checkpoints of PMN from [Here](https://github.com/birlrobotics/PMN#testing). I just shared the following files in that section instead of those (checkpoint_xxx_epoch.pth) showed in your screenshot. Please check it again.
> 
> ![Screenshot from 2020-09-12 16-13-45](https://user-images.githubusercontent.com/35102882/92991110-db42e700-f513-11ea-85f9-e42cf5e4f7cb.png)

Thank you for your patient help, it helped me a lot. It works!  Hope you have a nice day!

**Comment by Luke1962** [comment]
> Did you download the pre-trained checkpoints of PMN from [Here](https://github.com/birlrobotics/PMN#testing). I just shared the following files in that section instead of those (checkpoint_xxx_epoch.pth) showed in your screenshot. Please check it again.
> 
> ![Screenshot from 2020-09-12 16-13-45](https://user-images.githubusercontent.com/35102882/92991110-db42e700-f513-11ea-85f9-e42cf5e4f7cb.png)

Hi, in the provided link to PNM, the checkpoint folder is empty. Would you be so kind to update the repo with the file? thank you

**Comment by BIGJUN777** [comment]
@Luke1962 Hi there, I have double-checked the files and they are still available. 
![image](https://user-images.githubusercontent.com/35102882/184478625-8572082c-a4d5-4650-887f-1c06a5c2bf38.png)

**Comment by Luke1962** [comment]
Before any reply I want to say that I'm able to run the program, but with PNM disabled. Very Nice Job! Thank you.
However   I shall confirm that the file 'pnm_hico_chckpoint.pth' is NOT present inside PNM repo (by the way *.pth is into the .ignore file ...). Sorry may be the wrong post since it is a different file from the original post.
Anyway, from your answer, it seems instead that the file   - if I well understand - shall be generated with the command you have specified.
