### ISSUE TITLE
Visualize the training results

### ISSUE THREAD

**Issue by YaoDongAn** [birlrobotics/PMN#2]
Hello BIGJUN777, It's me again.
May I ask is there any code or tool to visualize the detection results on HICO_DET?
Thank you for your help.

**Comment by BIGJUN777** [comment]
Hello,
You can refer to the _./inference.py_ file to create the visualization detection results on HICO_DET as well as on V-COCO.  Before running the code, maybe you need to [reset the path](https://github.com/birlrobotics/PMN/blob/dca0dee799aa834580238dbcef1709dc54f197dd/inference.py#L71) to some files. The main tool for visualization is _./utils/vis_tool.py_. Check it if necessary.
